### ISSUE TITLE
可以直接使用echarts-for-weixin 吗？

### ISSUE THREAD

**Issue by EvaLotus** [baidu-smart-app/baidu-smart-app-echarts-demo#1]
如题，可以直接使用echarts-for-weixin 吗？库太大可以支持按需加载吗

**Comment by Ovilia** [comment]
不可以，微信小程序和百度智能小程序上的 ECharts 是两种不同的解决方案。
不支持按需加载，使用 4_7_0 版本大概是 1M 的大小。
