### ISSUE TITLE
formater使用到etpl模板语言，如何拓展自定义filter

### ISSUE THREAD

**Issue by Grace-xhw** [baidu-smart-app/baidu-smart-app-echarts-demo#4]
如题，业务需求需要保留4位小数，默认只有`raw|html|url` 三个filter，请问echart如何拓展自定义`filter`

**Comment by Ovilia** [comment]
formatter 的写法与原生 ECharts 有所不同，以下两种方式任选其一：

**第一种方式：回调函数**

参见 `pages/bar` 例子中 X 轴标签回调函数的方式：新增一个 `utils.sjs` 并且根据需要加回调函数的对象修改配置项，然后将 `index.swan` 改为：

```html
<import-sjs src="./utils.sjs" module="utils"></import-sjs>
<chart id="myChart" option="{{ utils.preprocessOption(option) }}" style="width: 100%; height: 500px; display: block"></chart>
```

**第二种方式：字符串模板**

从 `echarts_4_7_0` 版本起支持，例子参见「定制 formatter」，字符串模板参数是 `${params}`。参考本项目 `pages/formatter/index.js` 下的例子：

```js
formatter:
    '定制的 formatter：<br>'
    + '{{ for: ${params} as ${param} }}'
        + '{{ if: ${param.value} != null }}'
            + '<span style="width: 8px; height: 8px; border-radius: 4px; display: inline-block; '
                + 'margin-right: 5px; background-color: ${param.color}"></span>'
            + '${param.seriesName}: ${param.value}元<br>'
        + '{{ /if }}'
    + '{{ /for }}'
```

字符串模板参数是 `${params}`，模板语法详见 [etpl 模板语法](https://github.com/ecomfe/etpl/blob/master/doc/syntax.md)。需要注意的是，etpl 默认语法的开始指令和结束指令分别为 `<!--` 和 `-->`，而 ECharts 动态库中使用的是 `{{` 和 `}}`，所以在阅读以上文档的时候，需要将 `<!--` 和 `-->` 替换理解为 `{{` 和 `}}`。

> 提示：建议先用网页版 ECharts 调试图表，打印出 formatter 回调函数中的参数，这样可以方便理解上面的 param 对应的值。在网页版调试通过后，再迁移到小程序中使用字符串模板的形式作为回调函数。
