### ISSUE TITLE
dynamicLib://echarts_5_1_2/chart is not registered.

### ISSUE THREAD

**Issue by Gaozn** [baidu-smart-app/baidu-smart-app-echarts-demo#5]

**Comment by Ovilia** [comment]
如果你使用的是 5_1_2 版本的话，需要把 https://github.com/baidu-smart-app/baidu-smart-app-echarts-demo/blob/master/app.json#L39 这里设为 `"echarts_5_1_2"`。如果不能解决你的问题的话，请提供更多信息以方便我们定位问题。
