### ISSUE TITLE
百度文档中说明支持5.1.2版本，但是实际上小程序无法实现 ECharts5的功能

### ISSUE THREAD

**Issue by superman598** [baidu-smart-app/baidu-smart-app-echarts-demo#8]

**Comment by superman598** [comment]
例如：饼图中在 v5版本新增的圆角属性 borderRadius，在百度小程序中使用不生效
![image](https://github.com/baidu-smart-app/baidu-smart-app-echarts-demo/assets/67320727/fe7d1e67-bd79-45a0-b110-22a1d936c4ed)

**Comment by Ovilia** [comment]
`echarts_5_1_2` 内的 `echarts` 版本实际上还是 `4.x` 的，可能是发布的时候搞错了。现在可以使用 `echarts_5_5_1` 对应 5.5.1。
